# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version: '1.23.x'
                    cache-dependency-path: broker/go.sum

            -   name: Build broker
                run: make build
                working-directory: broker

            -   name: Test broker
                run: make test
                working-directory: broker
